// <auto-generated />
using Back_Vueapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Back_Vueapp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301160101_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Back_Vueapp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Casual and athletic shoes for daily use.",
                            Name = "Sneakers"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sturdy footwear covering the foot and ankle.",
                            Name = "Boots"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Light footwear for warm weather.",
                            Name = "Sandals"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Elegant shoes for special occasions or business.",
                            Name = "Formal"
                        });
                });

            modelBuilder.Entity("Back_Vueapp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "White/Red",
                            Description = "Classic retro sneakers.",
                            Name = "Air Max 90",
                            Price = 129.99m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Core Black",
                            Description = "High-performance running shoes.",
                            Name = "Ultraboost 22",
                            Price = 180.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Converse",
                            CategoryId = 1,
                            Color = "Black",
                            Description = "The iconic canvas sneakers.",
                            Name = "Chuck Taylor All Star",
                            Price = 65.00m,
                            Size = "39"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Timberland",
                            CategoryId = 2,
                            Color = "Wheat",
                            Description = "Classic waterproof work boots.",
                            Name = "6-Inch Premium",
                            Price = 199.95m,
                            Size = "44"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Dr. Martens",
                            CategoryId = 2,
                            Color = "Cherry Red",
                            Description = "Original 8-eye boot.",
                            Name = "1460 Smooth",
                            Price = 160.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Birkenstock",
                            CategoryId = 3,
                            Color = "Mocha",
                            Description = "Comfortable two-strap sandals.",
                            Name = "Arizona Soft Footbed",
                            Price = 135.00m,
                            Size = "40"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Crocs",
                            CategoryId = 3,
                            Color = "Navy",
                            Description = "Water-friendly and lightweight.",
                            Name = "Classic Clog",
                            Price = 49.99m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Allen Edmonds",
                            CategoryId = 4,
                            Color = "Walnut",
                            Description = "Premium leather oxford shoes.",
                            Name = "Fifth Avenue Cap-Toe",
                            Price = 395.00m,
                            Size = "43"
                        });
                });

            modelBuilder.Entity("Back_Vueapp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$e/y4QWJmOqYibW7h.3V3u.hW2YmZ4iJ0eLZ4p0hK8u/S0WpHC626q",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$e/y4QWJmOqYibW7h.3V3u.hW2YmZ4iJ0eLZ4p0hK8u/S0WpHC626q",
                            Role = "User",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("Back_Vueapp.Models.Product", b =>
                {
                    b.HasOne("Back_Vueapp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Back_Vueapp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
