// <auto-generated />
using Back_Vueapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Back_Vueapp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301183737_UpdateSeedDataToSpanishAndAddProducts")]
    partial class UpdateSeedDataToSpanishAndAddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Back_Vueapp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Calzado casual y deportivo para uso diario.",
                            Name = "Zapatillas"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Calzado resistente que cubre el pie y el tobillo.",
                            Name = "Botas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Calzado ligero para climas cálidos.",
                            Name = "Sandalias"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Zapatos elegantes para ocasiones especiales o negocios.",
                            Name = "Formal"
                        });
                });

            modelBuilder.Entity("Back_Vueapp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Blanco/Rojo",
                            Description = "Zapatillas retro clásicas.",
                            Name = "Air Max 90",
                            Price = 129.99m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Negro",
                            Description = "Zapatillas de running de alto rendimiento.",
                            Name = "Ultraboost 22",
                            Price = 180.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Converse",
                            CategoryId = 1,
                            Color = "Negro",
                            Description = "Las icónicas zapatillas de lona.",
                            Name = "Chuck Taylor All Star",
                            Price = 65.00m,
                            Size = "39"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Timberland",
                            CategoryId = 2,
                            Color = "Amarillo",
                            Description = "Clásicas botas de trabajo impermeables.",
                            Name = "6-Inch Premium",
                            Price = 199.95m,
                            Size = "44"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Dr. Martens",
                            CategoryId = 2,
                            Color = "Granate",
                            Description = "Bota original de 8 ojales.",
                            Name = "1460 Smooth",
                            Price = 160.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Birkenstock",
                            CategoryId = 3,
                            Color = "Marrón",
                            Description = "Sandalias cómodas de dos correas.",
                            Name = "Arizona Soft Footbed",
                            Price = 135.00m,
                            Size = "40"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Crocs",
                            CategoryId = 3,
                            Color = "Azul Marino",
                            Description = "Ligeras y resistentes al agua.",
                            Name = "Classic Clog",
                            Price = 49.99m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Allen Edmonds",
                            CategoryId = 4,
                            Color = "Nogal",
                            Description = "Zapatos oxford de piel premium.",
                            Name = "Fifth Avenue Cap-Toe",
                            Price = 395.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Azul",
                            Description = "Zapatillas de running versátiles.",
                            Name = "Pegasus 40",
                            Price = 130.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Blanco/Negro",
                            Description = "Zapatillas de estilo clásico.",
                            Name = "Samba OG",
                            Price = 110.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Vans",
                            CategoryId = 1,
                            Color = "Negro/Blanco",
                            Description = "Zapatillas de skate clásicas.",
                            Name = "Old Skool",
                            Price = 75.00m,
                            Size = "40"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Panama Jack",
                            CategoryId = 2,
                            Color = "Marrón",
                            Description = "Botas de piel resistentes.",
                            Name = "Classic Panama",
                            Price = 179.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Caterpillar",
                            CategoryId = 2,
                            Color = "Miel",
                            Description = "Botas robustas de alta durabilidad.",
                            Name = "Colorado",
                            Price = 145.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Havaianas",
                            CategoryId = 3,
                            Color = "Verde/Amarillo",
                            Description = "Las chanclas brasileñas más icónicas.",
                            Name = "Brasil Logo",
                            Price = 25.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Birkenstock",
                            CategoryId = 3,
                            Color = "Negro",
                            Description = "Sandalias de dedo elegantes y cómodas.",
                            Name = "Gizeh",
                            Price = 100.00m,
                            Size = "39"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Lottusse",
                            CategoryId = 4,
                            Color = "Negro",
                            Description = "Zapatos de vestir elegantes.",
                            Name = "Oxford Moderno",
                            Price = 220.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Sebago",
                            CategoryId = 4,
                            Color = "Burdeos",
                            Description = "Mocasines de piel hechos a mano.",
                            Name = "Mocasín Clásico",
                            Price = 185.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "New Balance",
                            CategoryId = 1,
                            Color = "Gris",
                            Description = "Zapatillas icónicas de estilo retro.",
                            Name = "574 Core",
                            Price = 110.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Asics",
                            CategoryId = 1,
                            Color = "Naranja",
                            Description = "Zapatillas de running con gran amortiguación.",
                            Name = "Novablast 3",
                            Price = 150.00m,
                            Size = "44"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Dr. Martens",
                            CategoryId = 2,
                            Color = "Negro",
                            Description = "Botas con plataforma de estilo rebelde.",
                            Name = "Jadon Platform",
                            Price = 220.00m,
                            Size = "39"
                        });
                });

            modelBuilder.Entity("Back_Vueapp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$ANwqtp51D/xBuSJ3Dqp4aO2WzV.1/.MFPpCPn8geRA6DrUaurkdAC",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$7VX46zQRtAtD3p8wdIPWSuHnm3hO6E6ePFIJuXHNJFY223DOfZdlu",
                            Role = "User",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("Back_Vueapp.Models.Product", b =>
                {
                    b.HasOne("Back_Vueapp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Back_Vueapp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
