// <auto-generated />
using System;
using Back_Vueapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Back_Vueapp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301193539_AddMoreSneakersWithDates")]
    partial class AddMoreSneakersWithDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Back_Vueapp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Calzado casual y deportivo para uso diario.",
                            Name = "Zapatillas"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Calzado resistente que cubre el pie y el tobillo.",
                            Name = "Botas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Calzado ligero para climas cálidos.",
                            Name = "Sandalias"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Zapatos elegantes para ocasiones especiales o negocios.",
                            Name = "Formal"
                        });
                });

            modelBuilder.Entity("Back_Vueapp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Blanco/Rojo",
                            CreatedAt = new DateTime(2026, 2, 19, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5446),
                            Description = "Zapatillas retro clásicas.",
                            Name = "Air Max 90",
                            Price = 129.99m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Negro",
                            CreatedAt = new DateTime(2026, 2, 24, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5456),
                            Description = "Zapatillas de running de alto rendimiento.",
                            Name = "Ultraboost 22",
                            Price = 180.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Converse",
                            CategoryId = 1,
                            Color = "Negro",
                            CreatedAt = new DateTime(2026, 2, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5459),
                            Description = "Las icónicas zapatillas de lona.",
                            Name = "Chuck Taylor All Star",
                            Price = 65.00m,
                            Size = "39"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Timberland",
                            CategoryId = 2,
                            Color = "Amarillo",
                            CreatedAt = new DateTime(2026, 1, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5466),
                            Description = "Clásicas botas de trabajo impermeables.",
                            Name = "6-Inch Premium",
                            Price = 199.95m,
                            Size = "44"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Dr. Martens",
                            CategoryId = 2,
                            Color = "Granate",
                            CreatedAt = new DateTime(2025, 12, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5469),
                            Description = "Bota original de 8 ojales.",
                            Name = "1460 Smooth",
                            Price = 160.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Birkenstock",
                            CategoryId = 3,
                            Color = "Marrón",
                            CreatedAt = new DateTime(2026, 2, 27, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5471),
                            Description = "Sandalias cómodas de dos correas.",
                            Name = "Arizona Soft Footbed",
                            Price = 135.00m,
                            Size = "40"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Crocs",
                            CategoryId = 3,
                            Color = "Azul Marino",
                            CreatedAt = new DateTime(2026, 2, 28, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5473),
                            Description = "Ligeras y resistentes al agua.",
                            Name = "Classic Clog",
                            Price = 49.99m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Allen Edmonds",
                            CategoryId = 4,
                            Color = "Nogal",
                            CreatedAt = new DateTime(2025, 11, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5474),
                            Description = "Zapatos oxford de piel premium.",
                            Name = "Fifth Avenue Cap-Toe",
                            Price = 395.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Azul",
                            CreatedAt = new DateTime(2026, 2, 14, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5476),
                            Description = "Zapatillas de running versátiles.",
                            Name = "Pegasus 40",
                            Price = 130.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Blanco/Negro",
                            CreatedAt = new DateTime(2026, 2, 9, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5478),
                            Description = "Zapatillas de estilo clásico.",
                            Name = "Samba OG",
                            Price = 110.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Vans",
                            CategoryId = 1,
                            Color = "Negro/Blanco",
                            CreatedAt = new DateTime(2026, 2, 4, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5480),
                            Description = "Zapatillas de skate clásicas.",
                            Name = "Old Skool",
                            Price = 75.00m,
                            Size = "40"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Panama Jack",
                            CategoryId = 2,
                            Color = "Marrón",
                            CreatedAt = new DateTime(2025, 10, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5481),
                            Description = "Botas de piel resistentes.",
                            Name = "Classic Panama",
                            Price = 179.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Caterpillar",
                            CategoryId = 2,
                            Color = "Miel",
                            CreatedAt = new DateTime(2025, 9, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5483),
                            Description = "Botas robustas de alta durabilidad.",
                            Name = "Colorado",
                            Price = 145.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Havaianas",
                            CategoryId = 3,
                            Color = "Verde/Amarillo",
                            CreatedAt = new DateTime(2026, 2, 26, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5485),
                            Description = "Las chanclas brasileñas más icónicas.",
                            Name = "Brasil Logo",
                            Price = 25.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Birkenstock",
                            CategoryId = 3,
                            Color = "Negro",
                            CreatedAt = new DateTime(2026, 2, 25, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5502),
                            Description = "Sandalias de dedo elegantes y cómodas.",
                            Name = "Gizeh",
                            Price = 100.00m,
                            Size = "39"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Lottusse",
                            CategoryId = 4,
                            Color = "Negro",
                            CreatedAt = new DateTime(2025, 8, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5504),
                            Description = "Zapatos de vestir elegantes.",
                            Name = "Oxford Moderno",
                            Price = 220.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Sebago",
                            CategoryId = 4,
                            Color = "Burdeos",
                            CreatedAt = new DateTime(2025, 7, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5506),
                            Description = "Mocasines de piel hechos a mano.",
                            Name = "Mocasín Clásico",
                            Price = 185.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "New Balance",
                            CategoryId = 1,
                            Color = "Gris",
                            CreatedAt = new DateTime(2026, 1, 30, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5507),
                            Description = "Zapatillas icónicas de estilo retro.",
                            Name = "574 Core",
                            Price = 110.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Asics",
                            CategoryId = 1,
                            Color = "Naranja",
                            CreatedAt = new DateTime(2026, 2, 17, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5510),
                            Description = "Zapatillas de running con gran amortiguación.",
                            Name = "Novablast 3",
                            Price = 150.00m,
                            Size = "44"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Dr. Martens",
                            CategoryId = 2,
                            Color = "Negro",
                            CreatedAt = new DateTime(2025, 6, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5511),
                            Description = "Botas con plataforma de estilo rebelde.",
                            Name = "Jadon Platform",
                            Price = 220.00m,
                            Size = "39"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Gris",
                            CreatedAt = new DateTime(2026, 1, 20, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5513),
                            Description = "Zapatillas exclusivas de diseño.",
                            Name = "Yeezy Boost 350",
                            Price = 220.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Rojo/Negro",
                            CreatedAt = new DateTime(2026, 1, 10, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5515),
                            Description = "Zapatillas legendarias de baloncesto.",
                            Name = "Air Jordan 1",
                            Price = 170.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Blanco",
                            CreatedAt = new DateTime(2025, 12, 31, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5517),
                            Description = "Zapatillas casuales de estilo retro.",
                            Name = "Court Vision",
                            Price = 75.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Blanco/Azul",
                            CreatedAt = new DateTime(2025, 12, 21, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5518),
                            Description = "Zapatillas clásicas de los 80.",
                            Name = "Forum Low",
                            Price = 100.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Vans",
                            CategoryId = 1,
                            Color = "Azul",
                            CreatedAt = new DateTime(2025, 12, 11, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5520),
                            Description = "Zapatillas de skate de caña alta.",
                            Name = "Sk8-Hi",
                            Price = 85.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Blanco",
                            CreatedAt = new DateTime(2025, 12, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5522),
                            Description = "Zapatillas retro versátiles.",
                            Name = "Continental 80",
                            Price = 90.00m,
                            Size = "40"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Blanco/Negro",
                            CreatedAt = new DateTime(2025, 11, 21, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5524),
                            Description = "Zapatillas vintage de baloncesto.",
                            Name = "Blazer Mid '77",
                            Price = 105.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "New Balance",
                            CategoryId = 1,
                            Color = "Verde",
                            CreatedAt = new DateTime(2025, 11, 11, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5527),
                            Description = "Zapatillas de running ultra cómodas.",
                            Name = "Fresh Foam",
                            Price = 140.00m,
                            Size = "44"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Converse",
                            CategoryId = 1,
                            Color = "Gris",
                            CreatedAt = new DateTime(2025, 11, 1, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5528),
                            Description = "Zapatillas casuales resistentes.",
                            Name = "Star Player",
                            Price = 70.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Asics",
                            CategoryId = 1,
                            Color = "Multi",
                            CreatedAt = new DateTime(2025, 10, 22, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5536),
                            Description = "Zapatillas icónicas con lengüeta dividida.",
                            Name = "Gel-Lyte III",
                            Price = 120.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Verde/Blanco",
                            CreatedAt = new DateTime(2025, 10, 12, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5538),
                            Description = "Zapatillas de culto muy populares.",
                            Name = "Dunk Low",
                            Price = 110.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Blanco/Verde",
                            CreatedAt = new DateTime(2025, 10, 2, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5540),
                            Description = "Zapatillas minimalistas clásicas.",
                            Name = "Stan Smith",
                            Price = 95.00m,
                            Size = "42"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Puma",
                            CategoryId = 1,
                            Color = "Rojo/Azul",
                            CreatedAt = new DateTime(2025, 9, 22, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5541),
                            Description = "Zapatillas modernas con estética chunky.",
                            Name = "RS-X Efekt",
                            Price = 120.00m,
                            Size = "41"
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Negro",
                            CreatedAt = new DateTime(2025, 9, 12, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5543),
                            Description = "Zapatillas de running equilibradas.",
                            Name = "Quest 5",
                            Price = 80.00m,
                            Size = "43"
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Blanco/Negro",
                            CreatedAt = new DateTime(2025, 9, 2, 19, 35, 37, 914, DateTimeKind.Utc).AddTicks(5545),
                            Description = "Zapatillas legendarias con puntera de goma.",
                            Name = "Superstar",
                            Price = 105.00m,
                            Size = "40"
                        });
                });

            modelBuilder.Entity("Back_Vueapp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$UyKNp7ynan6aai/fDzH0oesNG1foeMxZQD70cawuwxHtycDewqeEC",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$i6Bcz1sCvVRRykthrQ1m/.LEWQ54Bynb0ClEWh.8oylD/DSEWmxsG",
                            Role = "User",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("Back_Vueapp.Models.Product", b =>
                {
                    b.HasOne("Back_Vueapp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Back_Vueapp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
